kind: pipeline
name: pipeline
steps:
- name: publish
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master ]

- name: publish tag
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    tags: ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    event:
      - tag
